# config\packages\api_platform.yaml

api_platform:
    enable_docs: false
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']